# Generated by Django 4.2.8 on 2023-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato'), ('O', 'Outro')], max_length=1)),
                ('idade', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
